# Generated by Django 4.2.1 on 2023-06-02 21:04

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='category name')),
                ('slug', models.SlugField(editable=False, max_length=150, verbose_name='category url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('characteristic', models.JSONField(blank=True, default=dict, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'item category',
                'verbose_name_plural': 'item categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/item/')),
                ('characteristic', models.JSONField(blank=True, default=dict, null=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
